### ISSUE TITLE
Is there a way to support Python's cpuinfo package?

### ISSUE THREAD

**Issue by leeyiding** [nanovms/ops-examples#140]
I'm trying to get cpu information using Python's cpuinfo package, below is my code and configuration file. 

`test.py`
```python
from cpuinfo import get_cpu_info_json

print(get_cpu_info_json())
```

`config.json`
```json
{
    "MapDirs": {
        "./.venv/*": "/.local",
        "./usr/lib64/*": "/usr/lib/x86_64-linux-gnu",
        "./lib/*": "/lib/x86_64-linux-gnu",
        "./lib64/*": "/lib64"
    },
    "BaseVolumeSz": "2g",
    "RunConfig": {
        "CPUs": 6,
        "Memory": "2G",
        "Accel": true
    },
    "Args": [
        "test.py"
    ],
    "Files": [
        "test.py"
    ]
}
```

When running the image containing the above code, an error occurred. The specific error content is as follows:
```
running local instance
booting /root/.ops/images/python3 ...
en1: assigned 10.0.2.15
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    print(get_cpu_info_json())
  File "/.local/lib/python3.8/site-packages/cpuinfo/cpuinfo.py", line 2741, in get_cpu_info_json
    p1 = Popen(command, stdout=PIPE, stderr=PIPE, stdin=PIPE)
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 38] Function not implemented
en1: assigned FE80::88B3:7BFF:FE85:1B28
exit status 3
```

According to the error message, the problem seems to be with the subprocess package. I know Nanos Unikernel is a single process operating system, so I guess this is the reason why the error occurs.
If I really need to use Python's cpuinfo package, is there any way to solve this problem?

**Comment by eyberg** [comment]
you are right that shells out to get the info but even if you replaced that with a simple file read we don't have /proc/cpuinfo regardless

is there something specific in there that you are needing/looking for? I'm guessing a framework might be looking at it to ensure you have proper instructions - depending on what that specifically is it might be easy enough to monkey-patch it

**Comment by leeyiding** [comment]
Thank you for your response. I am actually trying to build an application running the Yolov8 model based on Nanos Unikernel. According to the [quick start](https://docs.ultralytics.com/quickstart/#use-ultralytics-with-python) guide for Yolov8, I used the following code for testing.

```python
from ultralytics import YOLO

# Create a new YOLO model from scratch
model = YOLO('yolov8n.yaml')

# Load a pretrained YOLO model (recommended for training)
model = YOLO('yolov8n.pt')

# Train the model using the 'coco128.yaml' dataset for 3 epochs
results = model.train(data='coco128.yaml', epochs=3)

# Evaluate the model's performance on the validation set
results = model.val()

# Perform object detection on an image using the model
results = model('https://ultralytics.com/images/bus.jpg')

# Export the model to ONNX format
success = model.export(format='onnx')
```

After solving the missing dependencies and dynamic link libraries, I encountered the error `RuntimeError: Failed to initialize cpuinfo!`. I suspect that [pytorch/cpuinfo](https://github.com/pytorch/cpuinfo) may not be adapted to Nanos, so I took the initiative to map the `proc/cpuinfo` file of the host machine to the corresponding location in the image. I am not sure if my operation is reasonable or correct, but after I did this, the error disappeared, and then the error message I mentioned in this issue appeared.

**Comment by eyberg** [comment]
so I made a quick little pytorch example here: https://github.com/nanovms/ops-examples/tree/master/python/python3.10/01-pytorch - we could also turn this into a pkg - happy to help you create that if you want

for your example where you explicitly import that cpuinfo pkg you could monkey patch it like so:

```
import sys
import cpuinfo
import numpy.distutils.cpuinfo
moduleys.modules['cpuinfo']= sys.modules['cpuinfo']
module.get_cpu_info = lambda: 'override'
sys.modules['cpuinfo'] = module
```

however that is not what pytorch is using,  https://github.com/pytorch/cpuinfo/blob/main/include/cpuinfo.h,

you can, as a hack, just cp over some proc:

```
mkdir proc
cp /proc/cpuinfo proc/.
```

```
{
  "Dirs": ["proc"]
}
```

most of these frameworks are just ensuring you have sse or avx or something like that

**Comment by leeyiding** [comment]
Thank you for your patient explanation, it's really great. I will try it your way first, and if I have any problems I will give you feedback. Have a great day!

**Comment by leeyiding** [comment]
Thank you very much. According to your tips, my problem was successfully solved through monkey patch.
