### ISSUE TITLE
add an nginx example

### ISSUE THREAD

**Issue by itwars** [nanovms/ops-examples#26]
Hi,
I would like to host my static blog using nginx package in nanovms. But I can't figure out?
BR

**Comment by eyberg** [comment]
hey - sorry just now seeing this - i whipped together a few basic localhost examples here -> https://github.com/nanovms/ops-examples/tree/master/nginx - if you want to push to the cloud - there are more instructions here -> https://nanovms.gitbook.io/ops/google_cloud - does this help?

**Comment by itwars** [comment]
Hi,
Exactly what I was looking for! Excellent!
Is there a way to build an .img ?

**Comment by eyberg** [comment]
you'll find those in ~/.ops/images - is there a diff. platform you want to try and boot it on?

**Comment by itwars** [comment]
Yep I've on prem kvm cluster, so I want to start .img using kvm (if it's possible).

**Comment by eyberg** [comment]
kvm should work out of the box using one of the flags ->

```
  -x, --accel              use cpu virtualization extension
```

**Comment by eyberg** [comment]
i'm going to close this on but if you run into any bugs or need more guides feel free to open another tkt - thanks!
