### ISSUE TITLE
Java package doesn't resolve names

### ISSUE THREAD

**Issue by Littlelies** [nanovms/ops-examples#56]
When I try to adapt HelloWorld.java like this:
```
import java.net.InetAddress;

public class HelloWorld {
   public static void main(String[] args) throws Exception {
        System.out.println("Hello World!");
        System.out.println(InetAddress.getByName("api.ipify.org"));        
   }
}
```
I get
```
Exception in thread "main" java.net.UnknownHostException: api.ipify.org: System error
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:924)
```
When I run the class inside docker, I have no problem. `Native Method` suggests Java Runtime is calling a kernel/glibc method to resolve host.

**Comment by eyberg** [comment]
@Littlelies there's a high likelihood we don't have the libnss .so's in that package - it's been a bit scattershot - can you open up a tkt on ops repo https://github.com/nanovms/ops and include the java pkg you are using? 1.8? 9? it should just be a task of adding the missing lib

**Comment by Littlelies** [comment]
Closing in favor of https://github.com/nanovms/ops/issues/590
