### ISSUE TITLE
Running an instance of NanoVM in Prod 

### ISSUE THREAD

**Issue by iamshreeram** [nanovms/ops-examples#77]
We would want to run a instance of nanovm in production (on our private cloud). Is there any documentation that discusses on soft points, metrics to monitor? 
Is there any telemetry that comes out of box from Nanovm?  Thanks!

cc: @eyberg

**Comment by eyberg** [comment]
what infrastructure/hypervisor are you using? we have relevant docs for each, if you're looking for some open source monitoring prometheus is a good choice that works out of the box, we also have https://nanovms.com/radar for something even more seamless

**Comment by iamshreeram** [comment]
1. We use a lot of KVMs, and few of ESXis.
2. I'll try using Prometheus as it is open source. Will migrate to radar, if we run into any issues. thanks!
